steps:
  # Reservations
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'africa-south1-docker.pkg.dev/sleepr-436202/reservations/production:latest',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'africa-south1-docker.pkg.dev/sleepr-436202/reservations/production:latest',
      ]

  # Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'africa-south1-docker.pkg.dev/sleepr-436202/notifications/production:latest',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'africa-south1-docker.pkg.dev/sleepr-436202/notifications/production:latest',
      ]

  # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'africa-south1-docker.pkg.dev/sleepr-436202/auth/production:latest',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'africa-south1-docker.pkg.dev/sleepr-436202/auth/production:latest',
      ]

  # Payments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'africa-south1-docker.pkg.dev/sleepr-436202/payments/production:latest',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'africa-south1-docker.pkg.dev/sleepr-436202/payments/production:latest',
      ]

options:
  logging: CLOUD_LOGGING_ONLY
